# Translations template for neutron.
# Copyright (C) 2014 ORGANIZATION
# This file is distributed under the same license as the neutron project.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2014.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: neutron 2015.1.dev465.g2dde360\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2014-11-25 06:08+0000\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 1.3\n"

#: neutron/policy.py:108
#, python-format
msgid ""
"Found deprecated policy rule:%s. Please consider upgrading your policy "
"configuration file"
msgstr ""

#: neutron/policy.py:166
#, python-format
msgid "Unable to find data type descriptor for attribute %s"
msgstr ""

#: neutron/agent/dhcp_agent.py:135
#, python-format
msgid ""
"Unable to %(action)s dhcp for %(net_id)s: there is a conflict with its "
"current state; please check that the network and/or its subnet(s) still "
"exist."
msgstr ""

#: neutron/agent/dhcp_agent.py:145 neutron/agent/dhcp_agent.py:214
#, python-format
msgid "Network %s has been deleted."
msgstr ""

#: neutron/agent/dhcp_agent.py:231
#, python-format
msgid ""
"Network %s may have been deleted and its resources may have already been "
"disposed."
msgstr ""

#: neutron/agent/dhcp_agent.py:364
#, python-format
msgid ""
"%(port_num)d router ports found on the metadata access network. Only the "
"port %(port_id)s, for router %(router_id)s will be considered"
msgstr ""

#: neutron/agent/dhcp_agent.py:585 neutron/agent/l3_agent.py:1979
#: neutron/agent/metadata/agent.py:411
#: neutron/services/metering/agents/metering_agent.py:268
msgid ""
"Neutron server does not support state report. State report for this agent"
" will be disabled."
msgstr ""

#: neutron/agent/l3_agent.py:528
#, python-format
msgid ""
"l3-agent cannot check service plugins enabled at the neutron server when "
"startup due to RPC error. It happens when the server does not support "
"this RPC API. If the error is UnsupportedVersion you can ignore this "
"warning. Detail message: %s"
msgstr ""

#: neutron/agent/l3_agent.py:540
#, python-format
msgid ""
"l3-agent cannot check service plugins enabled on the neutron server. "
"Retrying. Detail message: %s"
msgstr ""

#: neutron/agent/l3_agent.py:770
#, python-format
msgid "Info for router %s were not found. Skipping router removal"
msgstr ""

#: neutron/agent/l3_agent.py:1109
#, python-format
msgid "Unable to configure IP address for floating IP: %s"
msgstr ""

#: neutron/agent/rpc.py:102
msgid "DVR functionality requires a server upgrade."
msgstr ""

#: neutron/agent/securitygroups_rpc.py:67
#: neutron/agent/securitygroups_rpc.py:157
msgid "Driver configuration doesn't match with enable_security_group"
msgstr ""

#: neutron/agent/securitygroups_rpc.py:112
msgid ""
"Security group agent binding currently not set. This should be set by the"
" end of the init process."
msgstr ""

#: neutron/agent/securitygroups_rpc.py:184
msgid ""
"security_group_info_for_devices rpc call not supported by the server, "
"falling back to old security_group_rules_for_devices which scales worse."
msgstr ""

#: neutron/agent/linux/iptables_manager.py:155
#, python-format
msgid "Attempted to remove chain %s which does not exist"
msgstr ""

#: neutron/agent/linux/iptables_manager.py:235
#, python-format
msgid ""
"Tried to remove rule that was not there: %(chain)r %(rule)r %(wrap)r "
"%(top)r"
msgstr ""

#: neutron/agent/linux/iptables_manager.py:663
#, python-format
msgid "Attempted to get traffic counters of chain %s which does not exist"
msgstr ""

#: neutron/agent/linux/keepalived.py:361
msgid ""
"A previous instance of keepalived seems to be dead, unable to restart it,"
" a new instance will be spawned"
msgstr ""

#: neutron/agent/linux/ovs_lib.py:340
#, python-format
msgid "Found not yet ready openvswitch port: %s"
msgstr ""

#: neutron/agent/linux/ovs_lib.py:355
#, python-format
msgid "Found failed openvswitch port: %s"
msgstr ""

#: neutron/agent/linux/ovs_lib.py:414
#, python-format
msgid "ofport: %(ofport)s for VIF: %(vif)s is not a positive integer"
msgstr ""

#: neutron/agent/linux/ovs_lib.py:426
#, python-format
msgid "Unable to parse interface details. Exception: %s"
msgstr ""

#: neutron/agent/metadata/agent.py:171
msgid "Server does not support metadata RPC, fallback to using neutron client"
msgstr ""

#: neutron/agent/metadata/agent.py:286
msgid ""
"The remote metadata server responded with Forbidden. This response "
"usually occurs when shared secrets do not match."
msgstr ""

#: neutron/api/api_common.py:102
#, python-format
msgid ""
"Invalid value for pagination_max_limit: %s. It should be an integer "
"greater to 0"
msgstr ""

#: neutron/api/extensions.py:543
#, python-format
msgid "Did not find expected name \"%(ext_name)s\" in %(file)s"
msgstr ""

#: neutron/api/extensions.py:551
#, python-format
msgid "Extension file %(f)s wasn't loaded due to %(exception)s"
msgstr ""

#: neutron/api/extensions.py:592
#, python-format
msgid "Extension %s not supported by any of loaded plugins"
msgstr ""

#: neutron/api/extensions.py:604
#, python-format
msgid "Loaded plugins do not implement extension %s interface"
msgstr ""

#: neutron/api/rpc/agentnotifiers/dhcp_rpc_agent_api.py:66
#, python-format
msgid ""
"Unable to schedule network %s: no agents available; will retry on "
"subsequent port creation events."
msgstr ""

#: neutron/api/rpc/agentnotifiers/dhcp_rpc_agent_api.py:79
#, python-format
msgid ""
"Only %(active)d of %(total)d DHCP agents associated with network "
"'%(net_id)s' are marked as active, so notifications may be sent to "
"inactive agents."
msgstr ""

#: neutron/api/rpc/handlers/dhcp_rpc.py:83
#, python-format
msgid ""
"Action %(action)s for network %(net_id)s could not complete successfully:"
" %(reason)s"
msgstr ""

#: neutron/api/rpc/handlers/dhcp_rpc.py:127
#: neutron/api/rpc/handlers/dhcp_rpc.py:191
#, python-format
msgid "Network %s could not be found, it might have been deleted concurrently."
msgstr ""

#: neutron/api/rpc/handlers/dhcp_rpc.py:260
#, python-format
msgid "Updating lease expiration is now deprecated. Issued  from host %s."
msgstr ""

#: neutron/db/agents_db.py:99
#, python-format
msgid "%(agent_type)s agent %(agent_id)s is not active"
msgstr ""

#: neutron/db/agents_db.py:112
#, python-format
msgid "Configuration for agent %(agent_type)s on host %(host)s is invalid."
msgstr ""

#: neutron/db/l3_agentschedulers_db.py:106
msgid ""
"Time since last L3 agent reschedule check has exceeded the interval "
"between checks. Waiting before check to allow agents to send a heartbeat "
"in case there was a clock adjustment."
msgstr ""

#: neutron/db/l3_agentschedulers_db.py:128
#, python-format
msgid ""
"Rescheduling router %(router)s from agent %(agent)s because the agent did"
" not report to the server in the last %(dead_time)s seconds."
msgstr ""

#: neutron/db/l3_dvrscheduler_db.py:297
msgid "No active L3 agents found for SNAT"
msgstr ""

#: neutron/db/l3_hamode_db.py:406
#, python-format
msgid "The router %(router_id)s is bound multiple times on the agent %(host)s"
msgstr ""

#: neutron/db/securitygroups_rpc_base.py:359
#, python-format
msgid "No valid gateway port on subnet %s is found for IPv6 RA"
msgstr ""

#: neutron/db/vpn/vpn_db.py:660
#, python-format
msgid "vpnservice %s in db is already deleted"
msgstr ""

#: neutron/debug/debug_agent.py:123
#, python-format
msgid "Failed to delete namespace %s"
msgstr ""

#: neutron/notifiers/nova.py:186
msgid "Port ID not set! Nova will not be notified of port status change."
msgstr ""

#: neutron/notifiers/nova.py:242
#, python-format
msgid "Nova returned NotFound for event: %s"
msgstr ""

#: neutron/notifiers/nova.py:260
#, python-format
msgid "Nova event: %s returned with failed status"
msgstr ""

#: neutron/openstack/common/loopingcall.py:87
#, python-format
msgid "task %(func_name)s run outlasted interval by %(delay).2f sec"
msgstr ""

#: neutron/openstack/common/policy.py:248
#, python-format
msgid "Can not find policy directory: %s"
msgstr ""

#: neutron/openstack/common/service.py:356
#, python-format
msgid "pid %d not in child list"
msgstr ""

#: neutron/plugins/bigswitch/db/consistency_db.py:189
#, python-format
msgid ""
"Gave up waiting for consistency DB lock, trying to take it. Current hash "
"is: %s"
msgstr ""

#: neutron/plugins/bigswitch/db/consistency_db.py:205
msgid "Hash record already gone, no lock to clear."
msgstr ""

#: neutron/plugins/bigswitch/db/consistency_db.py:209
#, python-format
msgid "Another server already removed the lock. %s"
msgstr ""

#: neutron/plugins/linuxbridge/agent/linuxbridge_neutron_agent.py:83
msgid "VXLAN is enabled, a valid local_ip must be provided"
msgstr ""

#: neutron/plugins/linuxbridge/agent/linuxbridge_neutron_agent.py:97
msgid "Invalid Network ID, will lead to incorrect bridgename"
msgstr ""

#: neutron/plugins/linuxbridge/agent/linuxbridge_neutron_agent.py:104
msgid "Invalid VLAN ID, will lead to incorrect subinterface name"
msgstr ""

#: neutron/plugins/linuxbridge/agent/linuxbridge_neutron_agent.py:111
msgid "Invalid Interface ID, will lead to incorrect tap device name"
msgstr ""

#: neutron/plugins/linuxbridge/agent/linuxbridge_neutron_agent.py:120
#, python-format
msgid "Invalid Segmentation ID: %s, will lead to incorrect vxlan device name"
msgstr ""

#: neutron/plugins/linuxbridge/agent/linuxbridge_neutron_agent.py:520
#: neutron/plugins/linuxbridge/agent/linuxbridge_neutron_agent.py:554
#, python-format
msgid ""
"Option \"%(option)s\" must be supported by command \"%(command)s\" to "
"enable %(mode)s mode"
msgstr ""

#: neutron/plugins/linuxbridge/agent/linuxbridge_neutron_agent.py:548
msgid ""
"VXLAN muticast group must be provided in vxlan_group option to enable "
"VXLAN MCAST mode"
msgstr ""

#: neutron/plugins/ml2/managers.py:601
#, python-format
msgid "Failed to bind port %(port)s on host %(host)s"
msgstr ""

#: neutron/plugins/ml2/plugin.py:478
#, python-format
msgid ""
"In _notify_port_updated(), no bound segment for port %(port_id)s on "
"network %(network_id)s"
msgstr ""

#: neutron/plugins/ml2/plugin.py:639
msgid "A concurrent port creation has occurred"
msgstr ""

#: neutron/plugins/ml2/plugin.py:1114
#, python-format
msgid "Port %(port)s updated up by agent not found"
msgstr ""

#: neutron/plugins/ml2/plugin.py:1144
#, python-format
msgid "Port %s not found during update"
msgstr ""

#: neutron/plugins/ml2/rpc.py:67
#, python-format
msgid "Device %(device)s requested by agent %(agent_id)s not found in database"
msgstr ""

#: neutron/plugins/ml2/rpc.py:76
#, python-format
msgid ""
"Device %(device)s requested by agent %(agent_id)s on network "
"%(network_id)s not bound, vif_type: %(vif_type)s"
msgstr ""

#: neutron/plugins/ml2/drivers/helpers.py:141
#, python-format
msgid ""
"Allocate %(type)s segment from pool failed after %(number)s failed "
"attempts"
msgstr ""

#: neutron/plugins/ml2/drivers/mech_agent.py:74
#: neutron/plugins/ml2/drivers/mech_sriov/mech_driver.py:113
#, python-format
msgid "Attempting to bind with dead agent: %s"
msgstr ""

#: neutron/plugins/ml2/drivers/type_flat.py:131
#, python-format
msgid "No flat network found on physical network %s"
msgstr ""

#: neutron/plugins/ml2/drivers/type_gre.py:132
#, python-format
msgid "Gre endpoint with ip %s already exists"
msgstr ""

#: neutron/plugins/ml2/drivers/type_tunnel.py:142
#, python-format
msgid "%(type)s tunnel %(id)s not found"
msgstr ""

#: neutron/plugins/ml2/drivers/type_vlan.py:253
#, python-format
msgid "No vlan_id %(vlan_id)s found on physical network %(physical_network)s"
msgstr ""

#: neutron/plugins/ml2/drivers/type_vxlan.py:151
#, python-format
msgid "Vxlan endpoint with ip %s already exists"
msgstr ""

#: neutron/plugins/ml2/drivers/arista/mechanism_arista.py:77
#, python-format
msgid "'timestamp' command '%s' is not available on EOS"
msgstr ""

#: neutron/plugins/ml2/drivers/arista/mechanism_arista.py:331
#, python-format
msgid "VM id %(vmid)s not found for port %(portid)s"
msgstr ""

#: neutron/plugins/ml2/drivers/arista/mechanism_arista.py:348
#, python-format
msgid "Unknown device owner: %s"
msgstr ""

#: neutron/plugins/ml2/drivers/cisco/apic/apic_sync.py:66
#, python-format
msgid "Create network postcommit failed for network %s"
msgstr ""

#: neutron/plugins/ml2/drivers/cisco/apic/apic_sync.py:76
#, python-format
msgid "Create subnet postcommit failed for subnet %s"
msgstr ""

#: neutron/plugins/ml2/drivers/cisco/apic/apic_sync.py:89
#, python-format
msgid "Create port postcommit failed for port %s"
msgstr ""

#: neutron/plugins/ml2/drivers/cisco/apic/apic_sync.py:108
#, python-format
msgid "Add interface postcommit failed for port %s"
msgstr ""

#: neutron/plugins/ml2/drivers/cisco/nexus/nexus_db_v2.py:75
msgid "update_nexusport_binding called with no vlan"
msgstr ""

#: neutron/plugins/ml2/drivers/l2pop/mech_driver.py:155
msgid "Unable to retrieve the agent ip, check the agent configuration."
msgstr ""

#: neutron/plugins/ml2/drivers/l2pop/mech_driver.py:161
#, python-format
msgid "Port %(port)s updated by agent %(agent)s isn't bound to any segment"
msgstr ""

#: neutron/plugins/ml2/drivers/mech_bigswitch/driver.py:138
msgid "Ignoring port notification to controller because of missing host ID."
msgstr ""

#: neutron/plugins/nuage/syncmanager.py:298
#, python-format
msgid "Subnet %s not found in neutron for sync"
msgstr ""

#: neutron/plugins/nuage/syncmanager.py:316
#, python-format
msgid "Router %s not found in neutron for sync"
msgstr ""

#: neutron/plugins/nuage/syncmanager.py:328
#, python-format
msgid ""
"Route with destination %(dest)s and nexthop %(hop)s not found in neutron "
"for sync"
msgstr ""

#: neutron/plugins/nuage/syncmanager.py:342
#, python-format
msgid "Security group %s not found in neutron for sync"
msgstr ""

#: neutron/plugins/nuage/syncmanager.py:353
#, python-format
msgid "Security group rule %s not found in neutron for sync"
msgstr ""

#: neutron/plugins/nuage/syncmanager.py:363
#, python-format
msgid "Floating ip %s not found in neutron for sync"
msgstr ""

#: neutron/plugins/nuage/syncmanager.py:375
#, python-format
msgid "IP allocation for floating ip %s not found in neutron for sync"
msgstr ""

#: neutron/plugins/nuage/syncmanager.py:386
#, python-format
msgid "Net-partition %s not found in neutron for sync"
msgstr ""

#: neutron/plugins/nuage/syncmanager.py:396
#, python-format
msgid "VM port %s not found in neutron for sync"
msgstr ""

#: neutron/plugins/ofagent/agent/ofa_neutron_agent.py:284
#: neutron/plugins/openvswitch/agent/ovs_neutron_agent.py:1301
#, python-format
msgid "Unable to create tunnel port. Invalid remote IP: %s"
msgstr ""

#: neutron/plugins/ofagent/agent/ofa_neutron_agent.py:640
#: neutron/plugins/openvswitch/agent/ovs_neutron_agent.py:1023
#, python-format
msgid "VIF port: %s has no ofport configured, and might not be able to transmit"
msgstr ""

#: neutron/plugins/ofagent/agent/ofa_neutron_agent.py:747
#: neutron/plugins/openvswitch/agent/ovs_neutron_agent.py:1146
#, python-format
msgid "Device %s not defined on plugin"
msgstr ""

#: neutron/plugins/openvswitch/agent/ovs_dvr_neutron_agent.py:154
#, python-format
msgid ""
"L2 agent could not get DVR MAC address at startup due to RPC error.  It "
"happens when the server does not support this RPC API.  Detailed message:"
" %s"
msgstr ""

#: neutron/plugins/openvswitch/agent/ovs_dvr_neutron_agent.py:180
#, python-format
msgid ""
"L2 agent could not get DVR MAC address from server. Retrying. Detailed "
"message: %s"
msgstr ""

#: neutron/plugins/openvswitch/agent/ovs_neutron_agent.py:451
#, python-format
msgid "Action %s not supported"
msgstr ""

#: neutron/plugins/openvswitch/agent/ovs_neutron_agent.py:863
#, python-format
msgid ""
"Creating an interface named %(name)s exceeds the %(limit)d character "
"limitation. It was shortened to %(new_name)s to fit."
msgstr ""

#: neutron/scheduler/dhcp_agent_scheduler.py:80
#: neutron/scheduler/dhcp_agent_scheduler.py:89
msgid "No more DHCP agents"
msgstr ""

#: neutron/scheduler/dhcp_agent_scheduler.py:120
#, python-format
msgid "DHCP agent %s is not active"
msgstr ""

#: neutron/scheduler/l3_agent_scheduler.py:156
#, python-format
msgid "No routers compatible with L3 agent configuration on host %s"
msgstr ""

#: neutron/scheduler/l3_agent_scheduler.py:181
msgid "No active L3 agents"
msgstr ""

#: neutron/scheduler/l3_agent_scheduler.py:193
#, python-format
msgid "No L3 agents can host the router %s"
msgstr ""

#: neutron/services/firewall/fwaas_plugin.py:71
#, python-format
msgid "Firewall %(fw)s unexpectedly deleted by agent, status was %(status)s"
msgstr ""

#: neutron/services/firewall/agents/varmour/varmour_router.py:102
#, python-format
msgid "Ignoring multiple IPs on router port %s"
msgstr ""

#: neutron/services/firewall/agents/varmour/varmour_router.py:285
msgid "Unable to parse interface mapping."
msgstr ""

#: neutron/services/firewall/agents/varmour/varmour_router.py:288
msgid "Unable to read interface mapping."
msgstr ""

#: neutron/services/firewall/drivers/varmour/varmour_fwaas.py:109
msgid "Unsupported IP version rule."
msgstr ""

#: neutron/services/loadbalancer/agent_scheduler.py:110
#, python-format
msgid "No active lbaas agents for pool %s"
msgstr ""

#: neutron/services/loadbalancer/agent_scheduler.py:116
#, python-format
msgid "No lbaas agent supporting device driver %s"
msgstr ""

#: neutron/services/loadbalancer/drivers/common/agent_driver_base.py:72
#, python-format
msgid "Multiple lbaas agents found on host %s"
msgstr ""

#: neutron/services/loadbalancer/drivers/common/agent_driver_base.py:164
#, python-format
msgid ""
"Cannot update status: %(obj_type)s %(obj_id)s not found in the DB, it was"
" probably deleted concurrently"
msgstr ""

#: neutron/services/loadbalancer/drivers/embrane/driver.py:130
#, python-format
msgid "Subnet assigned to pool %s doesn't exist, backend port can't be created"
msgstr ""

#: neutron/services/loadbalancer/drivers/embrane/agent/lb_operations.py:110
#, python-format
msgid ""
"The load balancer %s had no physical representation, likely already "
"deleted"
msgstr ""

#: neutron/services/loadbalancer/drivers/haproxy/namespace_driver.py:172
#, python-format
msgid "Stats socket not found for pool %s"
msgstr ""

#: neutron/services/loadbalancer/drivers/haproxy/namespace_driver.py:214
#, python-format
msgid "Error while connecting to stats socket: %s"
msgstr ""

#: neutron/services/loadbalancer/drivers/radware/driver.py:298
#, python-format
msgid "pip nport delete failed: %r"
msgstr ""

#: neutron/services/loadbalancer/drivers/radware/driver.py:688
#, python-format
msgid "Fliping servers. Current is: %(server)s, switching to %(secondary)s"
msgstr ""

#: neutron/services/loadbalancer/drivers/radware/driver.py:709
#, python-format
msgid "vDirect server is not responding (%s)."
msgstr ""

#: neutron/services/loadbalancer/drivers/radware/driver.py:713
#, python-format
msgid "vDirect server is not active (%s)."
msgstr ""

#: neutron/services/vpn/device_drivers/cisco_csr_rest_client.py:115
#, python-format
msgid "%(method)s: Request timeout%(ssl)s (%(timeout).3f sec) for CSR(%(host)s)"
msgstr ""

#: neutron/services/vpn/device_drivers/cisco_ipsec.py:649
#, python-format
msgid "Unable to delete %(resource)s %(which)s: %(status)d"
msgstr ""

#: neutron/services/vpn/device_drivers/cisco_ipsec.py:731
#, python-format
msgid "Unable to find connection %s"
msgstr ""

